"""Generators for the official L1 circuit family.

The evaluation set is ``Bell``, ``GHZ-3``, ``GHZ-5``, ``QFT-4``, ``Grover-3``
and three random circuits, all drawn from the twelve-gate whitelist.  Only Bell
and GHZ-3 ship publicly; the rest are generated by the organisers from a private
seed.  So LoomQ generates its own of every shape and runs the full round-trip
check against all three targets — the hidden set differs only in its seed.
"""

import math
import random
from typing import List, Optional

from .gates import WHITELIST

_HEADER = 'OPENQASM 2.0;\ninclude "qelib1.inc";\n'


def _program(num_qubits: int, body: List[str], measure_all: bool = True) -> str:
    lines = [_HEADER.rstrip("\n"), "qreg q[%d];" % num_qubits, "creg c[%d];" % num_qubits]
    lines.extend(body)
    if measure_all:
        lines.append("measure q -> c;")
    return "\n".join(lines) + "\n"


def bell() -> str:
    """The two-qubit maximally entangled state."""
    return _program(2, ["h q[0];", "cx q[0], q[1];"])


def ghz(num_qubits: int = 3) -> str:
    """``(|0...0> + |1...1>) / sqrt(2)`` on ``num_qubits`` qubits."""
    if num_qubits < 2:
        raise ValueError("a GHZ state needs at least two qubits")
    body = ["h q[0];"]
    body += ["cx q[%d], q[%d];" % (index, index + 1) for index in range(num_qubits - 1)]
    return _program(num_qubits, body)


def qft(num_qubits: int = 4, prepare_uniform: bool = True) -> str:
    """Textbook QFT built from ``h``, ``cu1`` and a final ``swap`` reversal."""
    body = []  # type: List[str]
    if prepare_uniform:
        body += ["h q[%d];" % index for index in range(num_qubits)]
    for target in range(num_qubits - 1, -1, -1):
        body.append("h q[%d];" % target)
        for control in range(target - 1, -1, -1):
            angle = math.pi / (2 ** (target - control))
            body.append("cu1(%r) q[%d], q[%d];" % (angle, control, target))
    for index in range(num_qubits // 2):
        body.append("swap q[%d], q[%d];" % (index, num_qubits - 1 - index))
    return _program(num_qubits, body)


def grover(num_qubits: int = 3, marked: Optional[int] = None, iterations: int = 1) -> str:
    """Grover search with a phase oracle marking one basis state."""
    if num_qubits < 2:
        raise ValueError("Grover needs at least two qubits")
    if marked is None:
        marked = (1 << num_qubits) - 1
    controls = list(range(num_qubits - 1))
    target = num_qubits - 1

    def multi_controlled_z() -> List[str]:
        # Z on the target, controlled by the rest: H . (multi-controlled X) . H
        lines = ["h q[%d];" % target]
        if len(controls) == 1:
            lines.append("cx q[%d], q[%d];" % (controls[0], target))
        elif len(controls) == 2:
            lines.append("ccx q[%d], q[%d], q[%d];" % (controls[0], controls[1], target))
        else:
            raise ValueError("this generator covers up to three qubits")
        lines.append("h q[%d];" % target)
        return lines

    body = ["h q[%d];" % index for index in range(num_qubits)]
    for _ in range(iterations):
        flips = [index for index in range(num_qubits) if not (marked >> index) & 1]
        body += ["x q[%d];" % index for index in flips]
        body += multi_controlled_z()
        body += ["x q[%d];" % index for index in flips]
        body += ["h q[%d];" % index for index in range(num_qubits)]
        body += ["x q[%d];" % index for index in range(num_qubits)]
        body += multi_controlled_z()
        body += ["x q[%d];" % index for index in range(num_qubits)]
        body += ["h q[%d];" % index for index in range(num_qubits)]
    return _program(num_qubits, body)


def random_circuit(num_qubits: int = 4, depth: int = 12, seed: int = 0) -> str:
    """A whitelist-only random circuit, reproducible from ``seed``."""
    rng = random.Random(seed)
    single_free = ["h", "x", "s", "sdg", "t", "tdg"]
    single_param = ["rz", "ry"]
    body = []  # type: List[str]

    for _ in range(depth):
        choice = rng.random()
        if choice < 0.45:
            body.append("%s q[%d];" % (rng.choice(single_free), rng.randrange(num_qubits)))
        elif choice < 0.60:
            angle = rng.uniform(-math.pi, math.pi)
            body.append(
                "%s(%r) q[%d];" % (rng.choice(single_param), angle, rng.randrange(num_qubits))
            )
        elif choice < 0.85 and num_qubits >= 2:
            a, b = rng.sample(range(num_qubits), 2)
            if rng.random() < 0.6:
                body.append("cx q[%d], q[%d];" % (a, b))
            elif rng.random() < 0.5:
                body.append("swap q[%d], q[%d];" % (a, b))
            else:
                body.append("cu1(%r) q[%d], q[%d];" % (rng.uniform(-math.pi, math.pi), a, b))
        elif num_qubits >= 3:
            a, b, c = rng.sample(range(num_qubits), 3)
            body.append("ccx q[%d], q[%d], q[%d];" % (a, b, c))
        else:
            body.append("h q[%d];" % rng.randrange(num_qubits))
    return _program(num_qubits, body)


def official_suite() -> List[tuple]:
    """``(name, qasm)`` for the eight-circuit shape the rules describe."""
    return [
        ("bell", bell()),
        ("ghz3", ghz(3)),
        ("ghz5", ghz(5)),
        ("qft4", qft(4)),
        ("grover3", grover(3)),
        ("random-a", random_circuit(4, 14, seed=20260801)),
        ("random-b", random_circuit(5, 18, seed=20260815)),
        ("random-c", random_circuit(3, 20, seed=20260825)),
    ]


def whitelist_exercise() -> str:
    """One circuit that uses every gate in the whitelist at least once."""
    body = [
        "h q[0];",
        "x q[1];",
        "s q[0];",
        "sdg q[2];",
        "t q[1];",
        "tdg q[0];",
        "rz(%r) q[1];" % (math.pi / 3.0),
        "ry(%r) q[2];" % (math.pi / 5.0),
        "cx q[0], q[1];",
        "cu1(%r) q[1], q[2];" % (math.pi / 4.0),
        "swap q[0], q[2];",
        "ccx q[0], q[1], q[2];",
    ]
    assert set(WHITELIST) <= {line.split("(")[0].split()[0] for line in body}
    return _program(3, body)


__all__ = [
    "bell",
    "ghz",
    "grover",
    "official_suite",
    "qft",
    "random_circuit",
    "whitelist_exercise",
]
